<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6lhWiA9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6lhWiA9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6lhWiA9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6lhWiA9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6lhWiA9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6lhWiA9',
    'container.build_id' => 'f4540b91',
    'container.build_time' => 1597669420,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6lhWiA9');
