<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNP2nYhK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNP2nYhK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNP2nYhK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNP2nYhK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNP2nYhK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NP2nYhK',
    'container.build_id' => 'be0fd68c',
    'container.build_time' => 1597493107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNP2nYhK');
